version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - .:/app
    command: pytest -q
    environment:
      - PYTHONUNBUFFERED=1
    tty: true