name: Black

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  lint:
    name: Check formatting (Black)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Show versions
        run: |
          black --version

      - name: Run Black (check only)
        run: black --check --diff .